import type { CategoryId } from "@/lib/categories";

export type Tool = {
  slug: string;
  name: string;
  description: string;
  category: CategoryId;
  available: boolean;
  comingSoon?: boolean;
  iconColor: string;
};

export const TOOLS: Tool[] = [
  // ─────────── PDF (17) ───────────
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDF files into a single document. Drag, reorder, merge.",
    category: "pdf",
    available: true,
    iconColor: "text-rose-600",
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    description: "Rotate one or all pages of a PDF by 90°, 180°, or 270°.",
    category: "pdf",
    available: true,
    iconColor: "text-violet-600",
  },
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Combine JPG, PNG, or WebP images into a single PDF in any order.",
    category: "pdf",
    available: true,
    iconColor: "text-amber-600",
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    description: "Extract specific pages from a PDF using a page range like 1-3, 5, 7-10.",
    category: "pdf",
    available: true,
    iconColor: "text-blue-600",
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce PDF file size — choose low/medium/high compression. Server-side via Ghostscript.",
    category: "pdf",
    available: true,
    iconColor: "text-emerald-600",
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Export each PDF page as a JPG image. ZIP download for multi-page files.",
    category: "pdf",
    available: true,
    iconColor: "text-pink-600",
  },
  {
    slug: "watermark-pdf",
    name: "Watermark PDF",
    description: "Add a text watermark across every page — diagonal, with adjustable opacity.",
    category: "pdf",
    available: true,
    iconColor: "text-yellow-600",
  },
  {
    slug: "unlock-pdf",
    name: "Unlock PDF",
    description: "Remove password from a PDF (you must know the password).",
    category: "pdf",
    available: true,
    iconColor: "text-teal-600",
  },
  {
    slug: "protect-pdf",
    name: "Protect PDF",
    description: "Add a password to a PDF for read protection.",
    category: "pdf",
    available: true,
    iconColor: "text-indigo-600",
  },
  {
    slug: "pdf-to-markdown",
    name: "PDF to Markdown",
    description: "Extract PDF text with layout preserved — paste into ChatGPT, Claude, or Notion.",
    category: "pdf",
    available: true,
    iconColor: "text-emerald-600",
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    description: "Convert DOCX, DOC, or ODT to PDF using LibreOffice. Preserves formatting, fonts, images.",
    category: "pdf",
    available: true,
    iconColor: "text-blue-600",
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert PDF to editable Word document (.docx). Best for text-based PDFs.",
    category: "pdf",
    available: true,
    iconColor: "text-blue-600",
  },
  {
    slug: "pptx-to-pdf",
    name: "PowerPoint to PDF",
    description: "Convert PPTX, PPT, or ODP presentations to PDF. LibreOffice engine, preserves layout, fonts, animations as static slides.",
    category: "pdf",
    available: true,
    iconColor: "text-orange-600",
  },
  {
    slug: "pdf-to-pptx",
    name: "PDF to PowerPoint",
    description: "Convert PDF to PPTX with each page as a slide image. Preserves layout exactly. Best when editing isn't needed.",
    category: "pdf",
    available: true,
    iconColor: "text-orange-600",
  },
  {
    slug: "epub-to-pdf",
    name: "EPUB to PDF",
    description: "Convert EPUB ebooks to PDF for printing or PDF readers. Server-side Calibre engine with table of contents preserved.",
    category: "pdf",
    available: true,
    iconColor: "text-purple-600",
  },
  {
    slug: "pdf-to-epub",
    name: "PDF to EPUB",
    description: "Convert PDF to EPUB ebook for Kindle, Kobo, Apple Books. Server-side Calibre engine. Best for text-based PDFs.",
    category: "pdf",
    available: true,
    iconColor: "text-purple-600",
  },
  {
    slug: "screenshot-to-pdf",
    name: "Screenshot to PDF",
    description: "Paste screenshots with Ctrl/Cmd+V and combine into a single PDF. Browser-side, drag to reorder, fit-to-image or A4 page sizes.",
    category: "pdf",
    available: true,
    iconColor: "text-rose-600",
  },

  // ─────────── Image (13) ───────────
  {
    slug: "image-resizer",
    name: "Image Resizer",
    description: "Resize JPG, PNG, WebP images to any dimensions. Browser-side, no upload, no quality loss for downscaling.",
    category: "image",
    available: true,
    iconColor: "text-amber-600",
  },
  {
    slug: "image-compressor",
    name: "Image Compressor",
    description: "Compress JPG, PNG, WebP images with adjustable quality. Browser-side, no upload, real-time preview.",
    category: "image",
    available: true,
    iconColor: "text-amber-600",
  },
  {
    slug: "image-converter",
    name: "Image Converter",
    description: "Convert images between PNG, JPG, WebP, AVIF formats. Batch support, browser-side. No upload.",
    category: "image",
    available: true,
    iconColor: "text-amber-600",
  },
  {
    slug: "heic-to-jpg",
    name: "HEIC to JPG",
    description: "Convert iPhone HEIC photos to JPG or PNG. Browser-side, no upload — your photos stay on your device.",
    category: "image",
    available: true,
    iconColor: "text-amber-600",
  },
  {
    slug: "background-remover",
    name: "Background Remover",
    description: "Remove image background using AI in your browser. No upload, no signup, no daily limit. Powered by @imgly/background-removal.",
    category: "image",
    available: true,
    iconColor: "text-amber-600",
  },
  {
    slug: "image-cropper",
    name: "Image Cropper",
    description: "Crop images with preset aspect ratios (1:1, 4:3, 16:9, 9:16) or freeform. Browser-side, no upload, instant export to PNG or JPG.",
    category: "image",
    available: true,
    iconColor: "text-amber-600",
  },
  {
    slug: "image-upscaler",
    name: "Image Upscaler",
    description: "Enlarge images 2×, 3×, or 4× with smooth stepped resampling. Browser-side, no upload, no signup. Best for moderate enlargements of clean sources.",
    category: "image",
    available: true,
    iconColor: "text-amber-600",
  },
  {
    slug: "color-palette",
    name: "Color Palette Extractor",
    description: "Extract dominant colors from any image with median-cut quantization. Hex + RGB output, CSS array export. Browser-side.",
    category: "image",
    available: true,
    iconColor: "text-amber-600",
  },
  {
    slug: "svg-optimizer",
    name: "SVG Optimizer",
    description: "Strip comments, metadata, whitespace; round decimals; shorten colors. Live preview, size diff. Browser-side.",
    category: "image",
    available: true,
    iconColor: "text-amber-600",
  },
  {
    slug: "image-watermark",
    name: "Image Watermark",
    description: "Add text or image watermark to a photo. 6 positions, opacity, rotation, tile pattern. Browser-side, no upload.",
    category: "image",
    available: true,
    iconColor: "text-amber-600",
  },
  {
    slug: "favicon-generator",
    name: "Favicon Generator",
    description: "Upload 1 image → favicon pack: 12 PNG sizes + ICO + manifest.json + HTML snippet, zipped. Browser-side.",
    category: "image",
    available: true,
    iconColor: "text-amber-600",
  },
  {
    slug: "gif-maker",
    name: "GIF Maker",
    description: "Multiple images → animated GIF. Drag to reorder, frame delay, loop count. Browser-side via gif.js Web Worker.",
    category: "image",
    available: true,
    iconColor: "text-amber-600",
  },
  {
    slug: "exif-reader",
    name: "EXIF Reader & Stripper",
    description: "Read camera + GPS metadata from photos. Strip metadata before sharing for privacy. Browser-side.",
    category: "image",
    available: true,
    iconColor: "text-amber-600",
  },

  // ─────────── Developer (14) ───────────
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and minify JSON. Detects errors with line numbers. Browser-side, your data never leaves your device.",
    category: "dev",
    available: true,
    iconColor: "text-blue-600",
  },
  {
    slug: "base64-encoder",
    name: "Base64 Encoder",
    description: "Encode and decode Base64 strings. Supports text and file modes. Browser-side, instant.",
    category: "dev",
    available: true,
    iconColor: "text-blue-600",
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode JWT header and payload to inspect claims. Validates structure and expiry. Browser-side — tokens never leave your tab.",
    category: "dev",
    available: true,
    iconColor: "text-blue-600",
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, SHA-512 hashes. Text and file modes. Web Crypto API.",
    category: "dev",
    available: true,
    iconColor: "text-blue-600",
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate cryptographic UUID v4 single or in bulk (1-1000). One-click copy. Browser crypto.randomUUID.",
    category: "dev",
    available: true,
    iconColor: "text-blue-600",
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    description: "Test regular expressions live with match highlighting and capture groups. Supports JavaScript regex flags.",
    category: "dev",
    available: true,
    iconColor: "text-blue-600",
  },
  {
    slug: "timestamp-converter",
    name: "Timestamp Converter",
    description: "Convert between Unix timestamp (seconds/ms), ISO 8601, and human-readable date. Timezone-aware, live.",
    category: "dev",
    available: true,
    iconColor: "text-blue-600",
  },
  {
    slug: "diff-checker",
    name: "Text Diff Checker",
    description: "Compare two text blocks line-by-line with LCS algorithm. Color-coded additions/removals, ignore whitespace or case.",
    category: "dev",
    available: true,
    iconColor: "text-blue-600",
  },
  {
    slug: "gradient-generator",
    name: "CSS Gradient Generator",
    description: "Build linear, radial, or conic CSS gradients with live preview. Multi-stop, angle slider, Tailwind v4 ready.",
    category: "dev",
    available: true,
    iconColor: "text-blue-600",
  },
  {
    slug: "color-converter",
    name: "Color Converter",
    description: "Convert between HEX, RGB, HSL, HSV with live preview + WCAG contrast check.",
    category: "dev",
    available: true,
    iconColor: "text-blue-600",
  },
  {
    slug: "url-encoder",
    name: "URL Encoder / Decoder",
    description: "Percent-encode URL params or decode them. encodeURIComponent or encodeURI behavior.",
    category: "dev",
    available: true,
    iconColor: "text-blue-600",
  },
  {
    slug: "html-entity-encoder",
    name: "HTML Entity Encoder",
    description: "Escape HTML special chars (& < > \" ') or decode entities. Named, numeric, or all modes.",
    category: "dev",
    available: true,
    iconColor: "text-blue-600",
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter",
    description: "Pretty-print SQL across 11 dialects — MySQL, PostgreSQL, SQLite, BigQuery, Snowflake, more.",
    category: "dev",
    available: true,
    iconColor: "text-blue-600",
  },
  {
    slug: "yaml-json-converter",
    name: "YAML ↔ JSON Converter",
    description: "Convert YAML to JSON or JSON to YAML with adjustable indent. Inline error reporting.",
    category: "dev",
    available: true,
    iconColor: "text-blue-600",
  },

  // ─────────── Text (10) ───────────
  {
    slug: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences, paragraphs, and reading time. Live update as you type.",
    category: "text",
    available: true,
    iconColor: "text-emerald-600",
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    description: "Convert text to UPPERCASE, lowercase, Title Case, Sentence case, camelCase, snake_case, kebab-case.",
    category: "text",
    available: true,
    iconColor: "text-emerald-600",
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate Lorem Ipsum placeholder text — words, sentences, or paragraphs. Adjustable length.",
    category: "text",
    available: true,
    iconColor: "text-emerald-600",
  },
  {
    slug: "slug-generator",
    name: "Slug Generator",
    description: "Convert any text to URL-friendly slug. Strips diacritics (Vietnamese đ, ư, ê) and special chars.",
    category: "text",
    available: true,
    iconColor: "text-emerald-600",
  },
  {
    slug: "markdown-to-html",
    name: "Markdown to HTML",
    description: "Convert Markdown to clean HTML with GitHub-Flavored extensions. Live preview, copy HTML or download .html.",
    category: "text",
    available: true,
    iconColor: "text-emerald-600",
  },
  {
    slug: "find-replace",
    name: "Find & Replace",
    description: "Find and replace text with regex + capture groups. Live preview, match count, browser-side.",
    category: "text",
    available: true,
    iconColor: "text-emerald-600",
  },
  {
    slug: "sort-lines",
    name: "Sort Lines",
    description: "Sort text lines alphabetically, numerically, by length, naturally, or shuffle. Optional dedup + blank filter.",
    category: "text",
    available: true,
    iconColor: "text-emerald-600",
  },
  {
    slug: "remove-duplicates",
    name: "Remove Duplicate Lines",
    description: "Dedupe lines while preserving order. Case-sensitive option, whitespace trimming, keep-first vs keep-last.",
    category: "text",
    available: true,
    iconColor: "text-emerald-600",
  },
  {
    slug: "word-frequency",
    name: "Word Frequency Counter",
    description: "Count word, character, or line occurrences. Ranked top N, filter by length, drop stopwords, CSV export.",
    category: "text",
    available: true,
    iconColor: "text-emerald-600",
  },
  {
    slug: "line-numberer",
    name: "Line Numberer",
    description: "Add numbers, bullets, or custom prefix to each line. 12 presets + template with {n} {a} {r} variables.",
    category: "text",
    available: true,
    iconColor: "text-emerald-600",
  },

  // ─────────── Calculators (13) ───────────
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Generate cryptographically strong passwords. Length, symbols, numbers, exclude similar — all configurable.",
    category: "calc",
    available: true,
    iconColor: "text-indigo-600",
  },
  {
    slug: "qr-generator",
    name: "QR Code Generator",
    description: "Free QR codes for URL, WiFi, vCard, crypto, VietQR + 5 more. Custom shapes, gradient, logo overlay, scan-me frame. PNG or SVG.",
    category: "calc",
    available: true,
    iconColor: "text-indigo-600",
  },
  {
    slug: "qr-scanner",
    name: "QR Code Scanner",
    description: "Decode QR codes from an image upload or live camera. Detects URL, WiFi, vCard, email, phone, SMS, location, calendar event.",
    category: "calc",
    available: true,
    iconColor: "text-indigo-600",
  },
  {
    slug: "qr-batch",
    name: "Bulk QR Code Generator",
    description: "Generate up to 500 QR codes from a CSV in one click. Download as a ZIP of PNG / SVG. Browser-side, no upload.",
    category: "calc",
    available: true,
    iconColor: "text-indigo-600",
  },
  {
    slug: "age-calculator",
    name: "Age Calculator",
    description: "Calculate exact age in years, months, days, hours from a birth date. Detect leap-year birthdays.",
    category: "calc",
    available: true,
    iconColor: "text-indigo-600",
  },
  {
    slug: "tip-calculator",
    name: "Tip Calculator",
    description: "Split a bill, add a tip, round up — fast math for restaurants, taxis, and group meals. 7 currencies supported.",
    category: "calc",
    available: true,
    iconColor: "text-indigo-600",
  },
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    description: "Body Mass Index from height and weight with a healthy-range estimate. Metric and imperial supported. Browser-side.",
    category: "calc",
    available: true,
    iconColor: "text-indigo-600",
  },
  {
    slug: "currency-converter",
    name: "Currency Converter",
    description: "Convert between 28 major currencies with live mid-market rates. Cached for an hour, no signup, browser-side.",
    category: "calc",
    available: true,
    iconColor: "text-indigo-600",
  },
  {
    slug: "mortgage-calculator",
    name: "Mortgage Calculator",
    description: "Monthly payment, total interest, amortization schedule. Extra-payment what-if. Pure US fixed-rate math.",
    category: "calc",
    available: true,
    iconColor: "text-indigo-600",
  },
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Five percentage operations: % of, ratio, % change, increase, decrease. Live result as you type.",
    category: "calc",
    available: true,
    iconColor: "text-indigo-600",
  },
  {
    slug: "random-picker",
    name: "Random Picker",
    description: "Drop your list (one per line), pick N at random. Crypto-secure RNG. With/without replacement.",
    category: "calc",
    available: true,
    iconColor: "text-indigo-600",
  },
  {
    slug: "pomodoro-timer",
    name: "Pomodoro Timer",
    description: "25-min focus + 5-min break loop. Customizable durations, browser notifications, tab title countdown.",
    category: "calc",
    available: true,
    iconColor: "text-indigo-600",
  },
  {
    slug: "contrast-checker",
    name: "WCAG Contrast Checker",
    description: "Foreground/background colors → contrast ratio + WCAG AA/AAA rating + sample text preview at 5 sizes.",
    category: "calc",
    available: true,
    iconColor: "text-indigo-600",
  },

  // ─────────── AI (9 tools) ───────────
  {
    slug: "ai-summarizer",
    name: "AI Summarizer",
    description: "Summarize long text into 2-3 sentences, 4-6 sentences, or detailed bullets. Powered by Claude Haiku 4.5.",
    category: "ai",
    available: true,
    iconColor: "text-violet-600",
  },
  {
    slug: "ai-translator",
    name: "AI Translator",
    description: "Translate text into 20 languages while preserving formatting (markdown, bullets, paragraphs). Claude Haiku 4.5.",
    category: "ai",
    available: true,
    iconColor: "text-violet-600",
  },
  {
    slug: "ai-grammar-checker",
    name: "AI Grammar Checker",
    description: "Fix grammar, spelling, punctuation without changing your voice. See exactly what was changed and why.",
    category: "ai",
    available: true,
    iconColor: "text-violet-600",
  },
  {
    slug: "youtube-summarizer",
    name: "YouTube Video Summarizer",
    description: "Paste a YouTube URL and get a Claude Haiku summary of the transcript. Captions required. Free, daily quota of 10.",
    category: "ai",
    available: true,
    iconColor: "text-violet-600",
  },
  {
    slug: "chat-with-pdf",
    name: "Chat with PDF",
    description: "Ask questions about a PDF and get answers from Claude. PDF parsed in your browser — only extracted text reaches our server.",
    category: "ai",
    available: true,
    iconColor: "text-violet-600",
  },
  {
    slug: "translate-document",
    name: "Translate Document",
    description: "Translate text, markdown, HTML, CSV, JSON, or PDF documents into 20 languages while preserving formatting.",
    category: "ai",
    available: true,
    iconColor: "text-violet-600",
  },
  {
    slug: "qr-art-generator",
    name: "AI-Art QR Generator",
    description: "Stable Diffusion + ControlNet creates a scannable QR code blended into a custom artwork. Self-hosted GPU.",
    category: "ai",
    available: true,
    iconColor: "text-violet-600",
  },
  {
    slug: "ai-image-upscaler",
    name: "AI Image Upscaler",
    description: "Swin2SR transformer 4× upscale with detail enhancement. Better than bicubic for photos. Self-hosted GPU.",
    category: "ai",
    available: true,
    iconColor: "text-violet-600",
  },
  {
    slug: "ai-img2img",
    name: "AI Image Stylizer",
    description: "Stable Diffusion img2img: re-paint your photo as oil painting, anime, cyberpunk, watercolor, etc. Self-hosted GPU.",
    category: "ai",
    available: true,
    iconColor: "text-violet-600",
  },
];

export function getToolsByCategory(category: CategoryId): Tool[] {
  return TOOLS.filter((t) => t.category === category);
}

export function getTool(slug: string): Tool | undefined {
  return TOOLS.find((t) => t.slug === slug);
}
